version: '2'
services:
  app:
    image: indiehosters/known
    volumes:
      - ./data:/var/www/html/Uploads
    env_file:
      - ./env
  web:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/secrets:ro
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST
